[package]
name = "secret-toolkit-permit"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.0" }
secret-toolkit-utils = { path = "../utils" }
schemars = "0.7"
remain = "0.2.2"
