[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { git = "https://github.com/enigmampc/cosmwasm-0.14", branch = "impl-storage-prefix", features = [
    "iterator"
] }
cosmwasm-storage = { git = "https://github.com/enigmampc/cosmwasm-0.14", branch = "impl-storage-prefix", features = [
    "iterator"
] }
secret-toolkit-serialization = { path = "../serialization" }
