[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "1.0-rc1" }
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", tag = "1.0-rc1" }
