[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", branch = "debug-print" }
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", branch = "debug-print" }
secret-toolkit-serialization = { path = "../serialization" }

[dev-dependencies]
cosmwasm-vm = { package = "cosmwasm-sgx-vm", git = "https://github.com/enigmampc/SecretNetwork", branch = "debug-print" }
