[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "0.10" }
secret-toolkit-serialization = { path = "../serialization" }
