[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { version = "0.14.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.14.0", features = ["iterator"] }
secret-toolkit-serialization = { path = "../serialization" }
