[package]
name = "secret-toolkit-storage"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.2.1" }
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.2.1" }
secret-toolkit-serialization = { path = "../serialization" }
