[package]
name = "secret-toolkit"
version = "0.1.0"
edition = "2018"

[dependencies]
secret-toolkit-crypto = { path = "../crypto", optional = true }
secret-toolkit-incubator = { path = "../incubator", optional = true }
secret-toolkit-permit = { path = "../permit", optional = true }
secret-toolkit-serialization = { path = "../serialization", optional = true }
secret-toolkit-snip20 = { path = "../snip20", optional = true }
secret-toolkit-snip721 = { path = "../snip721", optional = true }
secret-toolkit-storage = { path = "../storage", optional = true }
secret-toolkit-utils = { path = "../utils", optional = true }

[features]
default = ["serialization", "snip20", "snip721", "storage", "utils"]

crypto = ["secret-toolkit-crypto"] # Not in default features because this is slow to compile
incubator = ["secret-toolkit-incubator", "serialization"] # Should never be in default features!
permit = ["secret-toolkit-permit", "crypto", "utils"] # Not in default features because it requires "crypto"
serialization = ["secret-toolkit-serialization"]
snip20 = ["secret-toolkit-snip20", "utils"]
snip721 = ["secret-toolkit-snip721", "utils"]
storage = ["secret-toolkit-storage", "serialization"]
utils = ["secret-toolkit-utils"]
