[package]
name = "secret-toolkit-snip20"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
schemars = "0.7"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "0.10" }
secret-toolkit-utils = { path = "../utils" }
