[package]
name = "secret-toolkit-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
schemars = "0.7"
cosmwasm-std = { git = "https://github.com/enigmampc/cosmwasm-0.14", branch = "impl-storage-prefix", features = [
    "iterator"
] }
