[package]
name = "secret-toolkit-incubator"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
siphasher = "0.3.0"
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.2.3" }
cosmwasm-storage = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.2.3" }
secret-toolkit-serialization = { path = "../serialization" }
