[package]
name = "secret-toolkit-serialization"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = "1.0"
bincode2 = { version = "2.0", optional = true }
cosmwasm-std = { version = "0.10.1", features = ["iterator"] }

[features]
default = ["json", "bincode2"]
json = []
